language: node_js

node_js:
  - "8.12.0"

script:
  - npm run build

deploy:
  provider: npm
  email: "palmflip@gmail.com"
  api_key: "0961d266-d89f-4398-aff3-4398f4175e78"
  skip_cleanup: true
  on:
    tags: true

cache:
  yarn: true
